#!/usr/bin/env python3
"""
Generate KML from a drone CSV log produced by drone_logger.py.

Uses lxml (already a DragonSync dependency) instead of simplekml, so the
kit image needs no extra package. KML is just XML in the OGC 2.2 namespace.
"""
import csv
import argparse
from collections import defaultdict
from lxml import etree

KML_NS = "http://www.opengis.net/kml/2.2"


def _coord_str(lon, lat, alt):
    return f"{lon},{lat},{alt}"


def csv_to_kml(input_csv, output_kml, tracks=False):
    """
    Reads 'input_csv' and writes 'output_kml'.
    If 'tracks' is False, creates individual Placemarks for each row.
    If 'tracks' is True, creates a separate LineString track per drone_id.
    """
    kml = etree.Element("{%s}kml" % KML_NS, nsmap={None: KML_NS})
    document = etree.SubElement(kml, "Document")

    if tracks:
        drone_coords = defaultdict(list)
        with open(input_csv, 'r') as f:
            reader = csv.DictReader(f)
            for row in reader:
                drone_id = row['drone_id']
                lat = float(row['lat'])
                lon = float(row['lon'])
                alt = float(row['alt'])
                drone_coords[drone_id].append((lon, lat, alt))

        for drone_id, coords in drone_coords.items():
            if not coords:
                continue
            placemark = etree.SubElement(document, "Placemark")
            etree.SubElement(placemark, "name").text = f"Track for {drone_id}"
            linestring = etree.SubElement(placemark, "LineString")
            etree.SubElement(linestring, "extrude").text = "1"
            etree.SubElement(linestring, "altitudeMode").text = "absolute"
            etree.SubElement(linestring, "coordinates").text = " ".join(
                _coord_str(lon, lat, alt) for (lon, lat, alt) in coords
            )

    else:
        with open(input_csv, 'r') as f:
            reader = csv.DictReader(f)
            for row in reader:
                drone_id  = row['drone_id']
                lat       = float(row['lat'])
                lon       = float(row['lon'])
                alt       = float(row['alt'])
                timestamp = row.get('timestamp', '')
                desc = (f"Drone: {drone_id}\n"
                        f"Time: {timestamp}\n"
                        f"Alt: {alt}\n"
                        f"Lat/Lon: {lat}, {lon}")

                placemark = etree.SubElement(document, "Placemark")
                etree.SubElement(placemark, "name").text = str(drone_id)
                etree.SubElement(placemark, "description").text = desc
                point = etree.SubElement(placemark, "Point")
                etree.SubElement(point, "altitudeMode").text = "absolute"
                etree.SubElement(point, "coordinates").text = _coord_str(lon, lat, alt)

    tree = etree.ElementTree(kml)
    tree.write(output_kml, pretty_print=True, xml_declaration=True, encoding="UTF-8")
    print(f"KML saved to {output_kml}")


def main():
    parser = argparse.ArgumentParser(description="Generate KML from a drone CSV file.")
    parser.add_argument("--csv", default="drone_log.csv", help="Path to the CSV file generated by the ZMQ logger")
    parser.add_argument("--kml", default="drone_data.kml", help="Output KML file path")
    parser.add_argument("--tracks", action="store_true",
                        help="If set, create linestring tracks instead of individual placemarks.")
    args = parser.parse_args()

    csv_to_kml(args.csv, args.kml, tracks=args.tracks)


if __name__ == "__main__":
    main()
